### ISSUE TITLE
Error.  Unexpected token

### ISSUE THREAD

**Issue by bonxz** [yafyz/nitrsnip#20]
Unexpected token? My Token is working.

This is my config
```
{
	"d_token": "",
	"d_gateway": "wss://gateway.discord.gg/?encoding=etf&v=9&compress=zlib-stream",
	"d_webhook": "/api/webhooks/",
	"d_err_webhook": "/api/webhooks/",
	"read_messages_on_redeem_account": true,
	"debug_webhook": "/api/webhooks/11111111/xx-xx",
	"use_multiple_tokens": true,
	"tokens_file": "files/tokens.txt",
	"show_messages": false,
	"cache_codes": true,
	"improve_latency": false,
	"force_webserver": false
}
```
´´´

```
/root/snip/http.js:4
    StatusCode = "0";
               ^

SyntaxError: Unexpected token =
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/root/snip/gift.js:4:26)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)```

**Comment by yafyz** [comment]
either old node version (<14) or the source is corrupted (try re-downloading)
if neither of those are the problem ¯\_(ツ)_/¯

**Comment by bonxz** [comment]
> either old node version (<14) or the source is corrupted (try re-downloading) if neither of those are the problem, ¯_(ツ)_/¯

which node version should i have at least?
![image](https://github.com/yafyz/nitrsnip/assets/61289944/036df42b-5eaa-47e2-abfc-f3ad3c0bd048)

**Comment by yafyz** [comment]
14 or newer

**Comment by bonxz** [comment]
fixed. thx
